/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao.animal;

import pacote.relatorio.RPAgendamento;
import pacote.relatorio.RPAnimal;
import pacote.relatorio.RPCliente;
import pacote.relatorio.RPProduto;
import visao.agendamento.AtualizarAgendamento;
import visao.agendamento.DeletarAgendamento;
import visao.produto.CadastroProdutos;
import visao.cliente.CadastroCliente;
import visao.agendamento.CadastroAgendamento;
import visao.agendamento.CadastroAgendamento;
import visao.agendamento.VisualizarAgendamento;
import visao.animal.AtualizarAnimal;
import visao.animal.AtualizarAnimal;
import visao.animal.CadastroAnimal;
import visao.animal.CadastroAnimal;
import visao.animal.CadastroAnimal;
import visao.cliente.AtualizarCliente;
import visao.cliente.AtualizarCliente;
import visao.cliente.AtualizarCliente;
import visao.cliente.AtualizarCliente;
import visao.cliente.CadastroCliente;
import visao.cliente.CadastroCliente;
import visao.cliente.CadastroCliente;
import visao.cliente.CadastroCliente;
import visao.cliente.DeletarCliente;
import visao.cliente.DeletarCliente;
import visao.cliente.VisualizarCliente;
import visao.cliente.VisualizarCliente;
import visao.cliente.VisualizarCliente;
import visao.produto.AtualizarProduto;
import visao.produto.DeletarProduto;
import visao.produto.VisualizarProduto;

/**
 *
 * @author Raquel Dornelas
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemMenuCadastroAnimal = new javax.swing.JMenuItem();
        itemMenuVisualizarAnimal = new javax.swing.JMenuItem();
        itemMenuAtualizarAnimal = new javax.swing.JMenuItem();
        itemMenuDeletarAnimal = new javax.swing.JMenuItem();
        menuCliente = new javax.swing.JMenu();
        itemMenuCliente = new javax.swing.JMenuItem();
        itemMenuVisualizarCliente = new javax.swing.JMenuItem();
        itemMenuAtualizarCliente = new javax.swing.JMenuItem();
        itemMenuDeletarCliente = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itemMenuCadastroProdutos = new javax.swing.JMenuItem();
        itemMenuVisualizarProduto = new javax.swing.JMenuItem();
        itemMenuAtualizarProduto = new javax.swing.JMenuItem();
        itemMenuDeletarProduto = new javax.swing.JMenuItem();
        menuAgendamento = new javax.swing.JMenu();
        itemMenuAgendamento = new javax.swing.JMenuItem();
        itemMenuVisualizarAgendamento = new javax.swing.JMenuItem();
        itemMenuAtualizarAgendamento = new javax.swing.JMenuItem();
        itemMenuDeletarAgendamento = new javax.swing.JMenuItem();
        menuRelatorios = new javax.swing.JMenu();
        itemMenuRelatorioAnimal = new javax.swing.JMenuItem();
        itemMenuRelatorioCliente = new javax.swing.JMenuItem();
        itemMenuRelatorioProduto = new javax.swing.JMenuItem();
        itemMenuRelatorioAgendamento = new javax.swing.JMenuItem();
        itemMenuSair = new javax.swing.JMenu();
        itemMenuSairSistema = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pet Shop");

        jPanel1.setBackground(new java.awt.Color(165, 236, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/logo.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Frase.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel2)))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 204, 204));

        jMenu1.setText("Animal");

        itemMenuCadastroAnimal.setText("Cadastrar Animal");
        itemMenuCadastroAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuCadastroAnimalActionPerformed(evt);
            }
        });
        jMenu1.add(itemMenuCadastroAnimal);

        itemMenuVisualizarAnimal.setText("Visualizar");
        itemMenuVisualizarAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuVisualizarAnimalActionPerformed(evt);
            }
        });
        jMenu1.add(itemMenuVisualizarAnimal);

        itemMenuAtualizarAnimal.setText("Atualizar");
        itemMenuAtualizarAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuAtualizarAnimalActionPerformed(evt);
            }
        });
        jMenu1.add(itemMenuAtualizarAnimal);

        itemMenuDeletarAnimal.setText("Deletar");
        itemMenuDeletarAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuDeletarAnimalActionPerformed(evt);
            }
        });
        jMenu1.add(itemMenuDeletarAnimal);

        jMenuBar1.add(jMenu1);

        menuCliente.setText("Cliente");

        itemMenuCliente.setText("Cadastrar Cliente");
        itemMenuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuClienteActionPerformed(evt);
            }
        });
        menuCliente.add(itemMenuCliente);

        itemMenuVisualizarCliente.setText("Visualizar");
        itemMenuVisualizarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuVisualizarClienteActionPerformed(evt);
            }
        });
        menuCliente.add(itemMenuVisualizarCliente);

        itemMenuAtualizarCliente.setText("Atualizar");
        itemMenuAtualizarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuAtualizarClienteActionPerformed(evt);
            }
        });
        menuCliente.add(itemMenuAtualizarCliente);

        itemMenuDeletarCliente.setText("Deletar");
        itemMenuDeletarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuDeletarClienteActionPerformed(evt);
            }
        });
        menuCliente.add(itemMenuDeletarCliente);

        jMenuBar1.add(menuCliente);

        jMenu2.setText("Produto");

        itemMenuCadastroProdutos.setText("Cadastrar Produto");
        itemMenuCadastroProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuCadastroProdutosActionPerformed(evt);
            }
        });
        jMenu2.add(itemMenuCadastroProdutos);

        itemMenuVisualizarProduto.setText("Visualizar");
        itemMenuVisualizarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuVisualizarProdutoActionPerformed(evt);
            }
        });
        jMenu2.add(itemMenuVisualizarProduto);

        itemMenuAtualizarProduto.setText("Atualizar");
        itemMenuAtualizarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuAtualizarProdutoActionPerformed(evt);
            }
        });
        jMenu2.add(itemMenuAtualizarProduto);

        itemMenuDeletarProduto.setText("Deletar");
        itemMenuDeletarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuDeletarProdutoActionPerformed(evt);
            }
        });
        jMenu2.add(itemMenuDeletarProduto);

        jMenuBar1.add(jMenu2);

        menuAgendamento.setText("Agendamento");

        itemMenuAgendamento.setText("Realizar Agendamento");
        itemMenuAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuAgendamentoActionPerformed(evt);
            }
        });
        menuAgendamento.add(itemMenuAgendamento);

        itemMenuVisualizarAgendamento.setText("Visualizar");
        itemMenuVisualizarAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuVisualizarAgendamentoActionPerformed(evt);
            }
        });
        menuAgendamento.add(itemMenuVisualizarAgendamento);

        itemMenuAtualizarAgendamento.setText("Atualizar");
        itemMenuAtualizarAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuAtualizarAgendamentoActionPerformed(evt);
            }
        });
        menuAgendamento.add(itemMenuAtualizarAgendamento);

        itemMenuDeletarAgendamento.setText("Deletar");
        itemMenuDeletarAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuDeletarAgendamentoActionPerformed(evt);
            }
        });
        menuAgendamento.add(itemMenuDeletarAgendamento);

        jMenuBar1.add(menuAgendamento);

        menuRelatorios.setText("Relatorios");

        itemMenuRelatorioAnimal.setText("Animal");
        itemMenuRelatorioAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuRelatorioAnimalActionPerformed(evt);
            }
        });
        menuRelatorios.add(itemMenuRelatorioAnimal);

        itemMenuRelatorioCliente.setText("Cliente");
        itemMenuRelatorioCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuRelatorioClienteActionPerformed(evt);
            }
        });
        menuRelatorios.add(itemMenuRelatorioCliente);

        itemMenuRelatorioProduto.setText("Produto");
        itemMenuRelatorioProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuRelatorioProdutoActionPerformed(evt);
            }
        });
        menuRelatorios.add(itemMenuRelatorioProduto);

        itemMenuRelatorioAgendamento.setText("Agendamento");
        itemMenuRelatorioAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuRelatorioAgendamentoActionPerformed(evt);
            }
        });
        menuRelatorios.add(itemMenuRelatorioAgendamento);

        jMenuBar1.add(menuRelatorios);

        itemMenuSair.setText("Sair");

        itemMenuSairSistema.setText("Sair do Sistema");
        itemMenuSairSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuSairSistemaActionPerformed(evt);
            }
        });
        itemMenuSair.add(itemMenuSairSistema);

        jMenuBar1.add(itemMenuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itemMenuSairSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuSairSistemaActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_itemMenuSairSistemaActionPerformed

    private void itemMenuDeletarAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuDeletarAgendamentoActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new DeletarAgendamento().setVisible(true);
    }//GEN-LAST:event_itemMenuDeletarAgendamentoActionPerformed

    private void itemMenuAtualizarAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuAtualizarAgendamentoActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new AtualizarAgendamento().setVisible(true);
    }//GEN-LAST:event_itemMenuAtualizarAgendamentoActionPerformed

    private void itemMenuVisualizarAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuVisualizarAgendamentoActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new VisualizarAgendamento().setVisible(true);
    }//GEN-LAST:event_itemMenuVisualizarAgendamentoActionPerformed

    private void itemMenuAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuAgendamentoActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new CadastroAgendamento().setVisible(true);
    }//GEN-LAST:event_itemMenuAgendamentoActionPerformed

    private void itemMenuDeletarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuDeletarProdutoActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new DeletarProduto().setVisible(true);
    }//GEN-LAST:event_itemMenuDeletarProdutoActionPerformed

    private void itemMenuAtualizarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuAtualizarProdutoActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new AtualizarProduto().setVisible(true);
    }//GEN-LAST:event_itemMenuAtualizarProdutoActionPerformed

    private void itemMenuVisualizarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuVisualizarProdutoActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new VisualizarProduto().setVisible(true);
    }//GEN-LAST:event_itemMenuVisualizarProdutoActionPerformed

    private void itemMenuCadastroProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuCadastroProdutosActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new CadastroProdutos().setVisible(true);
    }//GEN-LAST:event_itemMenuCadastroProdutosActionPerformed

    private void itemMenuDeletarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuDeletarClienteActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new DeletarCliente().setVisible(true);
    }//GEN-LAST:event_itemMenuDeletarClienteActionPerformed

    private void itemMenuAtualizarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuAtualizarClienteActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new AtualizarCliente().setVisible(true);
    }//GEN-LAST:event_itemMenuAtualizarClienteActionPerformed

    private void itemMenuVisualizarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuVisualizarClienteActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new VisualizarCliente().setVisible(true);
    }//GEN-LAST:event_itemMenuVisualizarClienteActionPerformed

    private void itemMenuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuClienteActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new CadastroCliente().setVisible(true);
    }//GEN-LAST:event_itemMenuClienteActionPerformed

    private void itemMenuDeletarAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuDeletarAnimalActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new DeletarAnimal().setVisible(true);
    }//GEN-LAST:event_itemMenuDeletarAnimalActionPerformed

    private void itemMenuAtualizarAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuAtualizarAnimalActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new AtualizarAnimal().setVisible(true);
    }//GEN-LAST:event_itemMenuAtualizarAnimalActionPerformed

    private void itemMenuVisualizarAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuVisualizarAnimalActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new VisualizarAnimal().setVisible(true);
    }//GEN-LAST:event_itemMenuVisualizarAnimalActionPerformed

    private void itemMenuCadastroAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuCadastroAnimalActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new CadastroAnimal().setVisible(true);
    }//GEN-LAST:event_itemMenuCadastroAnimalActionPerformed

    private void itemMenuRelatorioAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuRelatorioAgendamentoActionPerformed
        // TODO add your handling code here:
        RPAgendamento relatorioAgendamento = new RPAgendamento();
        relatorioAgendamento.gerarRelatorioTotal
       // ("E:\\Dados Ligia\\IFTM-Professora\\Disciplinas\\Programação Orientada Eventos\\Aulas\\Códigos\\17_Aula_CRUD_Relatórios\\src\\pacote\\relatorio\\RelatorioGeral.jasper");
         ("D:\\FACULDADE\\4° - Periodo\\POE\\Trabalhos\\Trabalho -3\\TrabalhoPOE3\\src\\pacote\\relatorio\\RelatorioAgendamento.jasper");
    }//GEN-LAST:event_itemMenuRelatorioAgendamentoActionPerformed

    private void itemMenuRelatorioAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuRelatorioAnimalActionPerformed
        // TODO add your handling code here:
        RPAnimal relatorioAnimal = new RPAnimal();
        relatorioAnimal.gerarRelatorioTotal
       // ("E:\\Dados Ligia\\IFTM-Professora\\Disciplinas\\Programação Orientada Eventos\\Aulas\\Códigos\\17_Aula_CRUD_Relatórios\\src\\pacote\\relatorio\\RelatorioGeral.jasper");
         ("D:\\FACULDADE\\4° - Periodo\\POE\\Trabalhos\\Trabalho -3\\TrabalhoPOE3\\src\\pacote\\relatorio\\RelatorioAnimal.jasper");
    }//GEN-LAST:event_itemMenuRelatorioAnimalActionPerformed

    private void itemMenuRelatorioClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuRelatorioClienteActionPerformed
        // TODO add your handling code here:
        RPCliente relatorioCliente = new RPCliente();
        relatorioCliente.gerarRelatorioTotal
       // ("E:\\Dados Ligia\\IFTM-Professora\\Disciplinas\\Programação Orientada Eventos\\Aulas\\Códigos\\17_Aula_CRUD_Relatórios\\src\\pacote\\relatorio\\RelatorioGeral.jasper");
         ("D:\\FACULDADE\\4° - Periodo\\POE\\Trabalhos\\Trabalho -3\\TrabalhoPOE3\\src\\pacote\\relatorio\\RelatorioCliente.jasper");
    }//GEN-LAST:event_itemMenuRelatorioClienteActionPerformed

    private void itemMenuRelatorioProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuRelatorioProdutoActionPerformed
        // TODO add your handling code here:
        RPProduto relatorioProduto = new RPProduto();
        relatorioProduto.gerarRelatorioTotal
       // ("E:\\Dados Ligia\\IFTM-Professora\\Disciplinas\\Programação Orientada Eventos\\Aulas\\Códigos\\17_Aula_CRUD_Relatórios\\src\\pacote\\relatorio\\RelatorioGeral.jasper");
         ("D:\\FACULDADE\\4° - Periodo\\POE\\Trabalhos\\Trabalho -3\\TrabalhoPOE3\\src\\pacote\\relatorio\\RelatorioProduto.jasper");
    }//GEN-LAST:event_itemMenuRelatorioProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemMenuAgendamento;
    private javax.swing.JMenuItem itemMenuAtualizarAgendamento;
    private javax.swing.JMenuItem itemMenuAtualizarAnimal;
    private javax.swing.JMenuItem itemMenuAtualizarCliente;
    private javax.swing.JMenuItem itemMenuAtualizarProduto;
    private javax.swing.JMenuItem itemMenuCadastroAnimal;
    private javax.swing.JMenuItem itemMenuCadastroProdutos;
    private javax.swing.JMenuItem itemMenuCliente;
    private javax.swing.JMenuItem itemMenuDeletarAgendamento;
    private javax.swing.JMenuItem itemMenuDeletarAnimal;
    private javax.swing.JMenuItem itemMenuDeletarCliente;
    private javax.swing.JMenuItem itemMenuDeletarProduto;
    private javax.swing.JMenuItem itemMenuRelatorioAgendamento;
    private javax.swing.JMenuItem itemMenuRelatorioAnimal;
    private javax.swing.JMenuItem itemMenuRelatorioCliente;
    private javax.swing.JMenuItem itemMenuRelatorioProduto;
    private javax.swing.JMenu itemMenuSair;
    private javax.swing.JMenuItem itemMenuSairSistema;
    private javax.swing.JMenuItem itemMenuVisualizarAgendamento;
    private javax.swing.JMenuItem itemMenuVisualizarAnimal;
    private javax.swing.JMenuItem itemMenuVisualizarCliente;
    private javax.swing.JMenuItem itemMenuVisualizarProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menuAgendamento;
    private javax.swing.JMenu menuCliente;
    private javax.swing.JMenu menuRelatorios;
    // End of variables declaration//GEN-END:variables
}
